### ISSUE TITLE
Java Assignment 0 - repo link missing 

### ISSUE THREAD

**Issue by icr8FreeCode** [LaunchCodeEducation/java-web-dev-curriculum#44]
[reviewing assignment 0](https://education.launchcode.org/java-web-dev-curriculum/assignments/hello-world/index.html)  learners are sent to [Canvas for a repo link](https://launchcode.instructure.com/courses/88) 
This repo link should be on the web page for Assignment 0 to minimize web hops

**Comment by tpenn** [comment]
All five assignments (0-4) refer learners to Canvas for their repo links.  Do you want this changed for all of them?
